FROM node:12.18.2 AS installer
COPY . .
WORKDIR /tests/projects/service
RUN yarn install

FROM installer as builder
ENTRYPOINT [ "yarn", "start" ]

FROM installer as tester
RUN echo "Hello, this is docker tester"
RUN mkdir -p /tests/projects/service/target/test-reports/
RUN yarn test-ci