# syntax=docker/dockerfile:1.4
FROM node:12.18.2 AS installer
COPY --link tests/projects/service/ /tests/projects/service/
WORKDIR /tests/projects/service
RUN yarn install

FROM installer as builder
ARG SOME_CREDENTIAL
ARG SOME_ENV
ENTRYPOINT [ "yarn", "start" ]

FROM installer as tester
RUN mkdir -p /tests/projects/service/target/test-reports/
RUN yarn test-ci