FROM bitnami/kubectl:1.26.7 as kubectl

FROM cypress/browsers:node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1

COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/

# fix missing/Outdated GPG errors, first we remove outdated repos and install the required tools
RUN DEBIAN_FRONTEND=noninteractive rm -f /etc/apt/sources.list.d/* && \
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update && \
    apt-get install --no-install-recommends -y apt-transport-https ca-certificates curl gnupg2 software-properties-common wget

# Add the Microsoft Edge repository and Google Chrome repository
RUN DEBIAN_FRONTEND=noninteractive wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/microsoft.gpg && \
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    install -o root -g root -m 644 /tmp/microsoft.gpg /etc/apt/trusted.gpg.d/ && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list && \
    rm -f /tmp/microsoft.gpg && \
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
