# syntax=docker/dockerfile:1.4
FROM node:12.18.2 AS installer
COPY --link tests/projects/job/ /tests/projects/job/
WORKDIR tests/projects/job/
RUN yarn install

FROM installer as builder
ENTRYPOINT [ "yarn", "start" ]
