name: 'Setup Helm chart testing infrastructure'
description: 'Creates an in-memory Kubernetes cluster with the required dependencies to test Helm charts'

inputs:
  traefik-chart-version:
    description: The version of the Traefik Helm chart to install
    required: true
  prometheus-chart-version:
    description: The version of the Prometheus Helm chart to install
    required: true
  sealed-secrets-chart-version:
    description: The version of the Sealed Secrets Helm chart to install
    required: true
  spark-operator-chart-version:
    description: The version of the Spark Operator Helm chart to install
    required: true

runs:
  using: composite
  steps:
    - uses: azure/setup-helm@v4.2.0
    - uses: helm/kind-action@v1.10.0

    - name: 'Add extra repositories'
      run: |
        helm repo add traefik https://helm.traefik.io/traefik
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
        helm repo add spark-operator https://kubeflow.github.io/spark-operator
        helm repo update
      shell: bash

    - run: helm install traefik traefik/traefik --version "$VERSION"
      shell: bash
      env:
        VERSION: ${{ inputs.traefik-chart-version }}

    - run: helm install kube-prometheus prometheus-community/kube-prometheus-stack --version "$VERSION"
      shell: bash
      env:
        VERSION: ${{ inputs.prometheus-chart-version }}

    - run: helm install sealed-secrets sealed-secrets/sealed-secrets --version "$VERSION"
      shell: bash
      env:
        VERSION: ${{ inputs.sealed-secrets-chart-version }}

    - run: helm install spark-operator spark-operator/spark-operator --version "$VERSION"
      shell: bash
      env:
        VERSION: ${{ inputs.spark-operator-chart-version }}
