name: build

on:
  push:
    branches-ignore: ['main']

jobs:
  Build_Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: /github/home/.local/share/virtualenvs/*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Run lint
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run run
